// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: proto/muntah.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMuntahRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *GetMuntahRequest) Reset() {
	*x = GetMuntahRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_muntah_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMuntahRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMuntahRequest) ProtoMessage() {}

func (x *GetMuntahRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_muntah_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMuntahRequest.ProtoReflect.Descriptor instead.
func (*GetMuntahRequest) Descriptor() ([]byte, []int) {
	return file_proto_muntah_proto_rawDescGZIP(), []int{0}
}

func (x *GetMuntahRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type GetMuntahResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Muntah []byte `protobuf:"bytes,1,opt,name=muntah,proto3" json:"muntah,omitempty"`
}

func (x *GetMuntahResponse) Reset() {
	*x = GetMuntahResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_muntah_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMuntahResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMuntahResponse) ProtoMessage() {}

func (x *GetMuntahResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_muntah_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMuntahResponse.ProtoReflect.Descriptor instead.
func (*GetMuntahResponse) Descriptor() ([]byte, []int) {
	return file_proto_muntah_proto_rawDescGZIP(), []int{1}
}

func (x *GetMuntahResponse) GetMuntah() []byte {
	if x != nil {
		return x.Muntah
	}
	return nil
}

var File_proto_muntah_proto protoreflect.FileDescriptor

var file_proto_muntah_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x75, 0x6e, 0x74, 0x61, 0x68, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x6e, 0x74, 0x61,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x2b,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x6e, 0x74, 0x61, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x75, 0x6e, 0x74, 0x61, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x6d, 0x75, 0x6e, 0x74, 0x61, 0x68, 0x32, 0x3e, 0x0a, 0x06, 0x4d,
	0x75, 0x6e, 0x74, 0x61, 0x68, 0x12, 0x34, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x6e, 0x74,
	0x61, 0x68, 0x12, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x6e, 0x74, 0x61, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x6e, 0x74, 0x61,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x61, 0x72, 0x6f, 0x75, 0x6e,
	0x2d, 0x64, 0x6a, 0x75, 0x64, 0x7a, 0x6d, 0x61, 0x6e, 0x2f, 0x6d, 0x75, 0x6e, 0x74, 0x61, 0x68,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_muntah_proto_rawDescOnce sync.Once
	file_proto_muntah_proto_rawDescData = file_proto_muntah_proto_rawDesc
)

func file_proto_muntah_proto_rawDescGZIP() []byte {
	file_proto_muntah_proto_rawDescOnce.Do(func() {
		file_proto_muntah_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_muntah_proto_rawDescData)
	})
	return file_proto_muntah_proto_rawDescData
}

var file_proto_muntah_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_muntah_proto_goTypes = []interface{}{
	(*GetMuntahRequest)(nil),  // 0: GetMuntahRequest
	(*GetMuntahResponse)(nil), // 1: GetMuntahResponse
}
var file_proto_muntah_proto_depIdxs = []int32{
	0, // 0: Muntah.GetMuntah:input_type -> GetMuntahRequest
	1, // 1: Muntah.GetMuntah:output_type -> GetMuntahResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_muntah_proto_init() }
func file_proto_muntah_proto_init() {
	if File_proto_muntah_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_muntah_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMuntahRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_muntah_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMuntahResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_muntah_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_muntah_proto_goTypes,
		DependencyIndexes: file_proto_muntah_proto_depIdxs,
		MessageInfos:      file_proto_muntah_proto_msgTypes,
	}.Build()
	File_proto_muntah_proto = out.File
	file_proto_muntah_proto_rawDesc = nil
	file_proto_muntah_proto_goTypes = nil
	file_proto_muntah_proto_depIdxs = nil
}
